finish assesment 1
asb1302/innopolis_go_assesment_1 pull request #1
Opened 2024-07-03 16:30 UTC by asb1302

2024-07-24 19:42 UTC, lelami requested changes

2024-07-24 19:42 UTC, lelami commented on cmd/web/main.go
> +	}()
В целом, можно было бы использовать один контекст `signal.NotifyContext`

2024-07-24 19:42 UTC, lelami commented on cmd/web/main.go
> +	application.Shutdown()
`application.Start(ctx)` уже обрабатывает кеш при останове приложения, так что здесь shutdown выглядит излишним)

2024-07-24 19:42 UTC, lelami commented on internal/app/app.go
> +	a.processCache()
лучше, чтобы `a.processCache()` при останове вызывался там же, где вызывается обычно, т.е. в `writeFiles`, чтобы только одна горутина управляла очисткой кеша

2024-07-24 19:42 UTC, lelami commented on internal/app/app.go
> +}
согласись, чтение из канала и запись в кеш - довольно легкая операция, так надо ли создавать для каждого файла 5+ воркеров для такой операции? к тому же, параллельно писать в кеш они все равно не могут из-за мьютекса
учитывая, что общая очередь у тебя одна, задержка скорее будет на стороне этой очереди, нежели на стороне канала файла, так что создавать для этих каналов много воркеров смысла нет

2024-07-24 19:42 UTC, lelami commented on internal/app/app.go
> +				time.Sleep(a.cfg.RetryInterval)
если файл будет недоступен по какой то причине, этот ретрай будет блокировать запись в другие файлы, т.е. им придется ждать, пока попытки записи именно в этот файл закончатся

2024-07-24 19:42 UTC, lelami commented on internal/app/app.go
> +				delete(a.cache, fileID)
вот тут самый главный баг всего приложения.
ты полностью копируешь кеш в новую мапу и записываешь сообщения из копии, а сам кеш какого-либо может успеть измениться за то время пока записывались кеши других файлов (особенно, если сработал ретрай)
записал те, которые скопировал - удалил эти сообщения + сообщения, которые успели прийти между копированием и записью в файл

я думаю, именно по этой причине у тебя валятся два теста
![Снимок экрана от 2024-07-24 23-53-04](https://github.com/user-attachments/assets/09ea297c-e10e-49df-b606-e4b16f26f5f7)
![Снимок экрана от 2024-07-24 23-53-41](https://github.com/user-attachments/assets/1ecda917-cc6d-410c-8347-4a525c6b4cfa)

2024-08-01 14:32 UTC, asb1302 commented on cmd/web/main.go
> +	}()
переделал на signal.NotifyContext https://github.com/asb1302/innopolis_go_assesment_1/pull/1/commits/d6fd4e90a1e5ac65c34a2854a447bb3418a9b7ae

2024-08-01 14:32 UTC, asb1302 commented on cmd/web/main.go
> +	application.Shutdown()
понял, спасибо, убрал

2024-08-03 14:08 UTC, lelami approved these changes

2024-08-06 16:12 UTC, merged